### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by Ethanhack** [thuxugang/doudizhu#6]
哪位大佬给一下修改choose函数，使choose实现玩家能选择自己出牌的方法

**Comment by thuxugang** [comment]
老铁，web分支里有

**Comment by Ethanhack** [comment]
作者大大，打开不了http://127.0.0.1:5000/ddz怎么办

 



------------------ 原始邮件 ------------------
发件人: "徐罡"<notifications@github.com>; 
发送时间: 2019年6月1日(星期六) 下午5:32
收件人: "thuxugang/doudizhu"<doudizhu@noreply.github.com>; 
抄送: "kelinxzggg"<836656395@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [thuxugang/doudizhu] help! (#6)




Closed #6.

**Comment by Ethanhack** [comment]
作者大大，作为编程小白，如果只想在master分支上修改choose函数，能实现我选择其中一个player出牌，其他复杂功能不想加，请问能给我提供一下思路吗？




------------------ 原始邮件 ------------------
发件人: "徐罡"<notifications@github.com>; 
发送时间: 2019年6月1日(星期六) 下午5:32
收件人: "thuxugang/doudizhu"<doudizhu@noreply.github.com>; 
抄送: "kelinxzggg"<836656395@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [thuxugang/doudizhu] help! (#6)




Closed #6.

**Comment by thuxugang** [comment]
将web分支server.py里面101行：app.run(host='10.1.0.189', port=5000, threaded=True)
改为：app.run(host='127.0.0.1', port=5000, threaded=True)

**Comment by Ethanhack** [comment]
谢谢作者大大的回答！ 实在不想耽误您的宝贵时间但由于水平有限，还是想问您实现master分支里控制一个玩家出牌
是运行master分支里的myclass、myutil、main_dzz以及web分支里的server.py吗？（因为运行方式可能不正确所以报错，作为小白
还不太能理解您的作品的其他功能，十分抱歉！）




------------------ 原始邮件 ------------------
发件人: "徐罡"<notifications@github.com>;
发送时间: 2019年6月2日(星期天) 下午2:13
收件人: "thuxugang/doudizhu"<doudizhu@noreply.github.com>;
抄送: "kelinxzggg"<836656395@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [thuxugang/doudizhu] help! (#6)




将web分支server.py里面101行：app.run(host='10.1.0.189', port=5000, threaded=True)
 改为：app.run(host='127.0.0.1', port=5000, threaded=True)

**Comment by thuxugang** [comment]
直接用web分支就行，master分支需要改的东西比较多，不支持人自动选择
首先python server.py启动程序
然后访问http://127.0.0.1:5000/ddz就可以操作啦~

**Comment by thuxugang** [comment]
不过你要是想在master改的话，没有前端显示的，在myutil.py里面，改def choose(next_move_types, next_moves, last_move_type, model)，master直接用的random
