### ISSUE TITLE
win10 py2.7 貌似下不了tensorflow（小白）

### ISSUE THREAD

**Issue by Y-joker** [thuxugang/doudizhu#7]

**Comment by thuxugang** [comment]
你也可以用py3.7，有冲突的改一下就行；或者不用强化学习就直接注释掉tensorflow相关的代码

**Comment by Y-joker** [comment]
嗷，作者大大，在Ubuntu上运行server.py ,点开始游戏没反应，终端显示"GET /ddz HTTP/1.1" 304 -等

**Comment by thuxugang** [comment]
小老弟，ip改没改呀？
将web分支server.py里面101行：app.run(host='10.1.0.189', port=5000, threaded=True)
改为：app.run(host='127.0.0.1', port=5000, threaded=True)

**Comment by thuxugang** [comment]
刚看了下，还有static下面index.html里面的10.1.0.189，都改为127.0.0.1

**Comment by Y-joker** [comment]
谢谢大大，还想问下web分支支持训练模型吗

**Comment by thuxugang** [comment]
强化学习的训练用rl_*那些分支，然后可以用web分支导入模型进行可视化来看结果

**Comment by Y-joker** [comment]
好的，谢谢

**Comment by Y-joker** [comment]
作者大大，训练数据在哪里，不知道该怎么导入-_-!，分支rl_pdqn貌似是python3运行的，用python2在from xx.xx improt xx中会出错。

**Comment by Y-joker** [comment]
大概知道了模型导入的方法了

**Comment by Y-joker** [comment]
感谢作者大大抽出宝贵的时间帮忙解答问题。

**Comment by thuxugang** [comment]
have fun
